Backend testing updates (#75)
* got backend coverage

* add tests to mstests

* readme testing updates

* Attempt at fixing dotnet tests

* fixing dotnet testing

* Better fixes for github action

* add timelimit for docker container

* Update dotnet.yml to wait 10 seconds for docker to catch up

* removed incompatible os

* change readme

* Try to add backend coverage to codecov

* fix syntax

* fixed list in brackets

* new codecov attempr

* fix yml syntax errors

* Fix file names

* add tests for atmos controller

* fixed family and properties tests

* Add unhappy initial conditions path

* Update dotnet.yml

* Add coverage and add backend to codecov

* Fix mysql loading for codecov

* update code coverage

* fix file names

* Try moving manual code cov file

* Reformat coverage files

* fix workflow syntax

* Rename files to get seen by codecov

* Add more unhappy path tests

* Manually add coverage for backend

* Manually add test coverage and remove workflow job

diff --git a/.github/workflows/dotnet.yml b/.github/workflows/dotnet.yml
--- a/.github/workflows/dotnet.yml
+++ b/.github/workflows/dotnet.yml
@@ -10,30 +10,48 @@ on:
 
 jobs:
   build:
-    continue-on-error: true
-    strategy:
-      matrix:
-        os: [ubuntu-latest, macos-latest, windows-latest]
-    runs-on: ${{ matrix.os }}
+    # strategy:
+    #   matrix:
+    #     os: [ubuntu-latest, macos-latest, windows-latest]
+    # runs-on: ${{ matrix.os }}
+    runs-on: ubuntu-latest # does not run on other platforms
     steps:
-    # Check out the code from the repository
-    - name: Checkout repository
-      uses: actions/checkout@v3
+      - name: Checkout repository
+        uses: actions/checkout@v3
 
-    # Set up .NET with version 6.0.x
-    - name: Setup .NET
-      uses: actions/setup-dotnet@v3
-      with:
-        dotnet-version: 6.0.x
+      - name: Setup .NET
+        uses: actions/setup-dotnet@v3
+        with:
+          dotnet-version: 8.0.x
 
-    # Restore the dependencies of the .NET project
-    - name: Restore dependencies
-      run: dotnet restore ./backend
+      - name: Restore dependencies
+        run: dotnet restore ./backend
 
-    # Build the project
-    - name: Build
-      run: dotnet build ./backend --no-restore
+      - name: Build
+        run: dotnet build ./backend --no-restore
 
-    # Run tests
-    - name: Test
-      run: dotnet test ./backend --no-build --verbosity normal
+      - name: Start database container
+        run: docker compose up -d mysql
+
+      - name: List running containers
+        run: docker ps -a
+
+      - name: Wait for database to be ready
+        run: |
+          for i in {1..30}; do
+            if docker exec $(docker ps -q --filter "name=mysql") mysqladmin ping -h"localhost" --silent; then
+              echo "Database is ready!"
+              sleep 10
+              exit 0
+            fi
+            echo "Waiting for database connection..."
+            sleep 2
+          done
+          echo "Database failed to start within the expected time."
+          exit 1
+
+      - name: Test
+        run: dotnet test  ./backend --collect "Code Coverage;Format=Cobertura" --no-build --verbosity normal
+
+      - name: Stop and remove database container
+        run: docker compose down
