add timelimit for docker container

diff --git a/.github/workflows/dotnet.yml b/.github/workflows/dotnet.yml
--- a/.github/workflows/dotnet.yml
+++ b/.github/workflows/dotnet.yml
@@ -10,47 +10,46 @@ on:
 
 jobs:
   build:
-    continue-on-error: true
     strategy:
       matrix:
         os: [ubuntu-latest, macos-latest, windows-latest]
     runs-on: ${{ matrix.os }}
     steps:
-    # Check out the code from the repository
-    - name: Checkout repository
-      uses: actions/checkout@v3
+      - name: Checkout repository
+        uses: actions/checkout@v3
 
-    # Set up .NET with version 6.0.x
-    - name: Setup .NET
-      uses: actions/setup-dotnet@v3
-      with:
-        dotnet-version: 8.0.x
+      - name: Setup .NET
+        uses: actions/setup-dotnet@v3
+        with:
+          dotnet-version: 8.0.x
 
-    # Restore the dependencies of the .NET project
-    - name: Restore dependencies
-      run: dotnet restore ./backend
+      - name: Restore dependencies
+        run: dotnet restore ./backend
 
-    # Build the project
-    - name: Build
-      run: dotnet build ./backend --no-restore
+      - name: Build
+        run: dotnet build ./backend --no-restore
 
+      - name: Start database container
+        run: docker compose up -d mysql
 
-    # Start database container
-    - name: Start database container
-      run: docker compose up -d mysql
+      - name: List running containers
+        run: docker ps -a
 
-    # Wait for the database to be ready
-    - name: Wait for database to be ready
-      run: |
-        until docker exec mysql mysqladmin ping -h"localhost" --silent; do
-          echo "Waiting for database connection..."
-          sleep 2
-        done
+      - name: Wait for database to be ready
+        run: |
+          for i in {1..30}; do
+            if docker exec $(docker ps -q --filter "name=mysql") mysqladmin ping -h"localhost" --silent; then
+              echo "Database is ready!"
+              exit 0
+            fi
+            echo "Waiting for database connection..."
+            sleep 2
+          done
+          echo "Database failed to start within the expected time."
+          exit 1
 
-    # Run tests
-    - name: Test
-      run: dotnet test ./backend --no-build --verbosity normal
+      - name: Test
+        run: dotnet test ./backend --no-build --verbosity normal
 
-    # Stop and clean up containers
-    - name: Stop and remove database container
-      run: docker compose down
+      - name: Stop and remove database container
+        run: docker compose down
